---
  - name: Combine overrides with release defaults
    set_fact:
      _releases: "{{ releases|combine(release_overrides, recursive=True) }}"
    when: release_overrides is defined

  - name: Set releases with user overrides
    set_fact:
      releases: "{{ _releases }}"
    when: release_overrides is defined

  - name: Combine overrides with utilities defaults
    set_fact:
      _utilities: "{{ utilities|combine(utilities_overrides, recursive=True) }}"
    when: utilities_overrides is defined

  - name: Set utility with user overrides
    set_fact:
      utilities: "{{ _utilities }}"
    when: utilities_overrides is defined

  - name: Generate directories
    file:
      path: "{{ netbootxyz_root }}"
      state: directory

  - name: Get current menu version
    shell: cat version.txt
    register: menu_version
    when:
      - generate_version_file | bool
    tags:
      - skip_ansible_lint

  - name: Set menu version
    set_fact:
      upstream_version: "{{ menu_version.stdout }}"
    when:
      - generate_version_file | bool

  - name: Generate version.ipxe for upstream
    template:
      src: "version.ipxe.j2"
      dest: "{{ netbootxyz_root }}/version.ipxe"
    when:
      - generate_version_file | bool

  - name: Generate netboot.xyz source files templates
    template:
      src: "{{ item.src }}"
      dest: "{{ netbootxyz_root }}/{{ item.path | regex_replace('.j2','') }}"
    with_filetree: "templates/menu/"
    when: item.state == "file"
    tags:
    - skip_ansible_lint

  - name: Retrieve pciids.ipxe
    get_url:
      url: "{{ pciids_url }}"
      dest: "{{ netbootxyz_root }}/pciids.ipxe"
